default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mm_development

test: &test
  <<: *default
  database: mm_test

production:
  <<: *default
  database: mm_production

cucumber:
  <<: *test
